# Generated by Django 5.0.6 on 2024-06-14 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ferramenta',
            name='img',
        ),
        migrations.RemoveField(
            model_name='plataforma',
            name='img',
        ),
    ]
