# Generated by Django 5.0.6 on 2024-06-15 01:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_remove_ferramenta_img_remove_plataforma_img'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plataforma',
            name='usuarios',
            field=models.ManyToManyField(related_name='plataformas', to=settings.AUTH_USER_MODEL),
        ),
    ]
